Exit animation set up
havascxistanbul/ycc-remastered pull request #2
Opened 2023-03-30 10:17 UTC by ravevy

Issue: #1

2023-03-30 10:19 UTC, byraptiye commented on src/components/Accordion/Accordion.tsx
> +console.log('lol');
Bu logu kaldıralım

2023-04-03 11:56 UTC, byraptiye requested changes

2023-04-03 11:56 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
>        x: '-200vw',
This is a not valid value. This metric max value is 100vw. You can check [here](https://www.w3schools.com/cssref/css_units.php).

2023-04-03 11:56 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '-200vw',
This is a not valid value. This metric max value is 100vw. You can check [here](https://www.w3schools.com/cssref/css_units.php).

2023-04-03 11:56 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '200vw',
This is a not valid value. This metric max value is 100vw. You can check [here](https://www.w3schools.com/cssref/css_units.php).

2023-04-03 11:56 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '200vw',
This is a not valid value. This metric max value is 100vw. You can check [here](https://www.w3schools.com/cssref/css_units.php).

2023-04-03 11:56 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '-200vw',
This is a not valid value. This metric max value is 100vw. You can check [here](https://www.w3schools.com/cssref/css_units.php).

2023-04-03 11:56 UTC, byraptiye commented on src/components/AnimatedRoutes/styles.scss
> +@import '../../styles/colors.scss';
Please use absolute paths. You can check [here](https://medhatdawoud.net/blog/paths-and-baseUrl-in-tsconfig.json)

2023-04-03 11:56 UTC, byraptiye commented on src/components/Animations/Home.tsx
>          x={267}
Maybe we can find a solution for this static variables. This not best practice but if we need use like this, please let me know.

2023-04-03 11:59 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
>        x: '-200vw',
Actually, it's not entirely correct to say that the value is not valid. We can use it this way, but the value of 100vw gives us a value of 1 viewport width. Since 200vw will provide 2 units, we do not need to use a value at this height. Increasing this value will affect the animation speed. Please don't forget this.

2023-04-03 11:59 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '-200vw',
Actually, it's not entirely correct to say that the value is not valid. We can use it this way, but the value of 100vw gives us a value of 1 viewport width. Since 200vw will provide 2 units, we do not need to use a value at this height. Increasing this value will affect the animation speed. Please don't forget this.

2023-04-03 11:59 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '200vw',
Actually, it's not entirely correct to say that the value is not valid. We can use it this way, but the value of 100vw gives us a value of 1 viewport width. Since 200vw will provide 2 units, we do not need to use a value at this height. Increasing this value will affect the animation speed. Please don't forget this.

2023-04-03 11:59 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '200vw',
Actually, it's not entirely correct to say that the value is not valid. We can use it this way, but the value of 100vw gives us a value of 1 viewport width. Since 200vw will provide 2 units, we do not need to use a value at this height. Increasing this value will affect the animation speed. Please don't forget this.

2023-04-03 11:59 UTC, byraptiye commented on src/components/AnimatedRoutes/AnimatedRoutes.tsx
> +      x: '-200vw',
Actually, it's not entirely correct to say that the value is not valid. We can use it this way, but the value of 100vw gives us a value of 1 viewport width. Since 200vw will provide 2 units, we do not need to use a value at this height. Increasing this value will affect the animation speed. Please don't forget this.

2023-04-04 12:50 UTC, ravevy commented on src/components/Animations/Home.tsx
>          x={267}
The values in animation move the image according to the static x value. We actually dont have to use the x attribute as we already have an initial value in animation variants. I can adjust the numbers in the animation suitable to the images x-axis position and remove static x attributes from the images.

2023-04-04 13:24 UTC, byraptiye commented on src/components/Animations/Home.tsx
>          x={267}
We don't need any unneccecary variables in project. Because of that, if we don't need a variable, please remove it. Also we have more static variables in this file and if we need to use this variables in static, we can keep it. But if we can find a solution for use this variables with dynamic, we have to do this.

2023-04-04 13:43 UTC, ravevy commented on src/components/Animations/Home.tsx
>          x={267}
You can find the mentioned solution in commit c171bba

2023-04-04 14:29 UTC, ravevy commented on src/components/Animations/Home.tsx
>          x={267}
I removed the unnecessary variables in commit aef3c66 . The variables I didn't delete are necessary to locate the images in the svg and there is no need for them to be dynamic.

2023-04-27 14:03 UTC, merged